### ISSUE TITLE
Getting 404 after startup

### ISSUE THREAD

**Issue by travismeyer** [wyveo/nginx-php-fpm#1]
Hey,

This is great, just can't seem to get around this issue. After running `sudo compose-build up` and opening my localhost, I get this error:

```
web_1      | 2017/04/13 00:16:55 [crit] 18#18: *1 connect() to unix:/run/php/php7.0-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 172.17.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "127.0.0.1"
web_1      | 2017/04/13 00:16:55 [error] 18#18: *1 open() "/usr/share/nginx/html/50x.html" failed (2: No such file or directory), client: 172.17.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock", host: "127.0.0.1"
web_1      | 172.17.0.1 - - [13/Apr/2017:00:16:55 +0000] "GET / HTTP/1.1" 404 564 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
```

Any ideas what might be going on?

**Comment by infinitysgame** [comment]
Try adding:

```
upstream fastcgi_backend {
    server 127.0.0.1:9000;
}
```
To the nginx `default.conf` file.

**Comment by travismeyer** [comment]
Yeah I saw that in a thread somewhere, but I'm getting this:

```
"upstream" directive is not allowed here in /etc/nginx/conf.d/default.conf
```

which shuts nginx down

**Comment by infinitysgame** [comment]
Try adding the to the `/etc/nginx/nginx.conf` file instead.

**Comment by travismeyer** [comment]
```
"upstream" directive is not allowed here in /etc/nginx/nginx.conf:13
```

**Comment by infinitysgame** [comment]
Sorry, did you place it inside the `http` block?

**Comment by travismeyer** [comment]
No longer getting that error on nginx startup, but its still not able to connect to the `php7.0-fpm.sock` file

```
web_1      | 2017/04/13 22:15:42 [crit] 18#18: *1 connect() to unix:/run/php/php7.0-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 172.17.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "localhost"
web_1      | 2017/04/13 22:15:42 [error] 18#18: *1 open() "/usr/share/nginx/html/50x.html" failed (2: No such file or directory), client: 172.17.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock", host: "localhost"
```

**Comment by infinitysgame** [comment]
Sorry. Quick question, are you in fact trying to use the [craftcms-docker](https://github.com/wyveo/craftcms-docker) repo?

**Comment by travismeyer** [comment]
I repurposed that repo to work with Craft 3--its a work in progress. We're having all sorts of dependency issues and my machine doesn't have enough storage for vagrant, so I'm trying to make Docker work.

So far, after beta12, its working really great. I get all sorts of "unknown errors" in the dashboard on craft3 when I try to run it on my system configs, but my docker containers run great.

Why do you ask?

--
Travis Meyer

(sent via mobile)

**Comment by travismeyer** [comment]
Sorry I just realized you're not Brandon from pixel and tonic (been communicating back and forth with him), I actually fixed this issue! I'll put some notes in the issue thread and close it out asap

Thanks Colin!

--
Travis Meyer

(sent via mobile)

**Comment by infinitysgame** [comment]
I noticed that you said you ran the `sudo compose-build up` command, and also that that repo's `default.conf` is configured for php 7.0.x not php 7.1 which is the image it's pulling.

I'll update it soon.

**Comment by travismeyer** [comment]
Yep, thats the fix exactly

--
Travis Meyer

(sent via mobile)

**Comment by infinitysgame** [comment]
Cool. I'll close this issue and update the other repo. Will also create a Craft 3 (Beta) branch too.
