### ISSUE TITLE
Getting 500 after startup with Laravel 

### ISSUE THREAD

**Issue by Codingjames** [wyveo/nginx-php-fpm#13]
**I used these command with nomal index.php It's ok.**
**When i deployed laravel i got error 500. Help me please**

```
docker pull wyveo/nginx-php-fpm
docker run --name ams -p 8001:80  -v /var/www/html/nginx-php/ams-v2/public:/usr/share/nginx/html wyveo/nginx-php-fpm:latest
```

**Comment by colinwilson** [comment]
Have you tried mounting a custom [laravel nginx configuration](https://laravel.com/docs/8.x/deployment#nginx) at `/etc/nginx/conf.d/default.conf`?

**Comment by Codingjames** [comment]
> Have you tried mounting a custom [laravel nginx configuration](https://laravel.com/docs/8.x/deployment#nginx) at `/etc/nginx/conf.d/default.conf`?

Thank you, It's work
