### ISSUE TITLE
php7.0-mcrypt missing?

### ISSUE THREAD

**Issue by steshaw** [wyveo/nginx-php-fpm#3]
It looks like `php7.0-mcrypt` is missing from the recent changes to `php70` branch. Was it intentional?

**Comment by colinwilson** [comment]
Nope. Accidental due to cutting'n'pasting the docker file from the `latest` branch, php 7.2 ([where mcrypt is depreciated](https://wiki.php.net/rfc/mcrypt-viking-funeral)).

fixed by 558f71d

**Comment by steshaw** [comment]
Thankyou
