### ISSUE TITLE
Installing PHP Modules 

### ISSUE THREAD

**Issue by derekmaxson** [wyveo/nginx-php-fpm#31]
Is there a method to add additional PHP modules into this docker at runtime?   I see that I could fork the code and add them into Dockerfile.

I'm building a Moodle docker and it requires xmlrpc and a couple other modules.  I'm using docker-compose to configure.

**Comment by colinwilson** [comment]
Yep. Forking and adding to the `Dockerfile` is probably best. My personal preference is to keep the pre-installed modules to those common/essential.

**Comment by derekmaxson** [comment]
Thanks @colinwilson for a great container!

**Comment by LTroya** [comment]
Hi @derekmaxson, can you give a hint about how to extend this image? I will appreciate any hint
