### ISSUE TITLE
Make a docker tag for php 7.2

### ISSUE THREAD

**Issue by tmulry** [wyveo/nginx-php-fpm#4]
Please make a Docker tag for php72.  This allows me to lock in my team to a specific version of extensions, nginx etc.  Otherwise the dev who just joined the project ends up with a different php config from the dev who hasn't rebuilt his image in the past 4 months.

**Comment by colinwilson** [comment]
Just added a new php72 branch (via https://github.com/wyveo/nginx-php-fpm/commit/dc10461c880b2bbe437c0f662fd02a815e385b58) and triggered a Docker Hub build. The php72 tag should be available shortly.

Any issues let me know.
