### ISSUE TITLE
Why are we using supervisord?

### ISSUE THREAD

**Issue by simplenotezy** [wyveo/nginx-php-fpm#41]
I notice you're trying to run nginx and php-fpm under supervisord - which makes little sense.

nginx and php-fpm already do what supervisord does - or am I missing something?

**Comment by ww9** [comment]
Hi! Docker can only have one main process called ENTRYPOINT.

So if we want to run multiple processes in a single container it is convenient to use a process manager such as supervisord.

I hope that answers your question.
