### ISSUE TITLE
Composer upgrade on PHP 7.x images

### ISSUE THREAD

**Issue by gdevdeiv** [wyveo/nginx-php-fpm#44]
Hi there,

I would like to ask if there is any particular reason for which Composer is locked to version 1 on PHP 7.x images.
I am going to fork the repository to upgrade those for personal use, would like to know as I can PR easily.

Thanks,
David.

**Comment by colinwilson** [comment]
@gdevdeiv No. No particular reason actually. AFAIK it's 100% backwards compatible with version 1. PRs more than welcome. Thank you.

**Comment by maxdmyers** [comment]
@colinwilson I've opened #47, #48, #49, #50 and #51 to bring composer up to v2 for all php 7.x branches.

**Comment by colinwilson** [comment]
@maxdmyers Awesome. Thank you so much for contributing. Will merge these shortly.

**Comment by maxdmyers** [comment]
@colinwilson Thank you!

**Comment by maxdmyers** [comment]
@colinwilson Do you have an idea when you might able to merge these? I'm working on testing some things and want to make sure I update to use the correct base image again when you're finished.

**Comment by colinwilson** [comment]
@maxdmyers merged now. Thanks again for these PR's. Much appreciated 👍
