### ISSUE TITLE
Fails when run in OpenShift

### ISSUE THREAD

**Issue by premkumar-gg** [wyveo/nginx-php-fpm#8]
Running the image plain as such in OpenShift results in this error

```
sed: couldn't open temporary file /etc/nginx/sednQggFi: Permission denied
--
  | Error: Can't drop privilege as nonroot user
  | For help, use /usr/local/bin/supervisord -h
```

It makes sense as it is against the standard guidelines that a container when run should not require root privileges. [https://opensource.com/article/18/3/just-say-no-root-containers](https://opensource.com/article/18/3/just-say-no-root-containers)

Happy to spend some time fixing it, if anybody advises on how to go about it.

**Comment by colinwilson** [comment]
I plan to update the images to accommodate this standard as soon as I find some time.
