### ISSUE TITLE
php.ini changes done aren't reflected 

### ISSUE THREAD

**Issue by shehanster** [wyveo/nginx-php-fpm#9]
Even though the php file is set as `php_conf=/etc/php/7.4/fpm/php.ini`  the  loaded configuration file is as follows
`php -i | grep 'Loaded Configuration File'
Loaded Configuration File => /etc/php/7.4/cli/php.ini`

how can we fix this?

**Comment by colinwilson** [comment]
This is the configuration loaded from/for the CLI. nginx (or apache) will load the `/etc/php/7.4/fpm/php.ini` configuration file. See [here](https://www.php.net/manual/en/function.php-ini-loaded-file.php) for details on how to check which config is loaded.
